name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Download Forge MDK
        run: |
          wget https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-mdk.zip
          unzip forge-1.12.2-14.23.5.2847-mdk.zip -d forge-mdk
          cp forge-mdk/gradlew .
          cp -r forge-mdk/gradle .
          chmod +x gradlew
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: pawpatrol-jar
          path: build/libs/*.jar
